stages:
  
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages
  
  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model/base_model_updated.h5
      - artifacts/prepare_base_model/base_model.h5
  
  train_model:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps:
      - src/deepClassifier/pipeline/stage_03_training.py
      - src/deepClassifier/components/prepare_callbacks.py
      - artifacts/prepare_base_model/base_model.h5
      - artifacts/data_ingestion/PetImages
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evalueate_model:
    cmd: python src\deepClassifier\pipeline\stage_04_evaluation.py
    deps:
      - src\deepClassifier\pipeline\stage_04_evaluation.py
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - score.json:
        cache: false